app = "ecto-sessions-demo"
kill_signal = "SIGTERM"
kill_timeout = 20
processes = []

[build]
  dockerfile = "Dockerfile.prod"

[deploy]
  release_command = "/app/bin/ecto_sessions_demo eval EctoSessionsDemo.ReleaseTasks.migrate"

[experimental]
  auto_rollback = false
  private_network = true

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    method = "GET"
    path = "/"
    grace_period = "10s"
    interval = "20s"
    timeout = "5s"

