app = "ecto-sessions-demo"
kill_signal = "SIGTERM"
kill_timeout = 20
processes = []

[build]
  dockerfile = "Dockerfile.prod"

[deploy]
  release_command = "/app/bin/ecto_sessions_demo eval EctoSessionsDemo.ReleaseTasks.migrate"

[experimental]
  auto_rollback = false
  private_network = true

[[services]]
  internal_port = 4000
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 300
    soft_limit = 200
    type = "connections"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.tcp_checks]]
    grace_period = "15s"
    interval = "15s"
    restart_limit = 2
    timeout = "4s"
